"use client";

import { BadgeCheck, LoaderCircle, Play } from "lucide-react";
import { useState } from "react";

import { Botao } from "@/components/ui/botao";
import type { EntradaSessaoBeta, SessaoBeta } from "@/types/beta";

export function PainelSessaoBeta({ sessao, operacao, apto, aoIniciar, aoFinalizar }: { sessao: SessaoBeta | null; operacao: string | null; apto: boolean; aoIniciar: (entrada: EntradaSessaoBeta) => Promise<unknown>; aoFinalizar: () => Promise<unknown> }) {
  const [nome, setNome] = useState("Beta operacional");
  const [alvo, setAlvo] = useState("Windows 10/11 · máquina limpa");
  return <section className="rounded-md border border-[#e0e6e5] bg-white"><div className="border-b border-[#e7ebea] px-5 py-4"><h2 className="text-[12px] font-semibold text-[#303738]">Sessão de homologação</h2><p className="mt-1 text-[8.5px] leading-4 text-[#7d8687]">Registre uma rodada independente para cada máquina, conta ou release candidate.</p></div><div className="p-5">{sessao ? <div className="space-y-3"><div className="grid grid-cols-2 gap-3"><div className="rounded-md border border-[#e3e8e7] bg-[#fafbfb] p-3"><span className="text-[7px] uppercase tracking-[0.08em] text-[#91999a]">Sessão</span><strong className="mt-1 block text-[10px] text-[#3b4445]">{sessao.nome}</strong></div><div className="rounded-md border border-[#e3e8e7] bg-[#fafbfb] p-3"><span className="text-[7px] uppercase tracking-[0.08em] text-[#91999a]">Alvo</span><strong className="mt-1 block text-[10px] text-[#3b4445]">{sessao.alvo}</strong></div></div><p className="text-[8px] leading-4 text-[#737d7d]">{sessao.mensagem}</p><Botao variante="primario" disabled={!apto || Boolean(operacao) || sessao.status === "aprovada"} onClick={() => void aoFinalizar()}>{operacao === "finalizar" ? <LoaderCircle className="size-3.5 animate-spin" /> : <BadgeCheck className="size-3.5" />} Aprovar sessão</Botao></div> : <div><div className="grid grid-cols-2 gap-3"><label><span className="mb-1.5 block text-[8px] font-medium text-[#596364]">Nome da rodada</span><input value={nome} onChange={(evento) => setNome(evento.target.value)} className="foco-acessivel h-10 w-full rounded-md border border-[#dfe5e4] px-3 text-[9px] text-[#3f4748]" /></label><label><span className="mb-1.5 block text-[8px] font-medium text-[#596364]">Máquina e cenário</span><input value={alvo} onChange={(evento) => setAlvo(evento.target.value)} className="foco-acessivel h-10 w-full rounded-md border border-[#dfe5e4] px-3 text-[9px] text-[#3f4748]" /></label></div><Botao className="mt-3" variante="primario" disabled={!nome.trim() || !alvo.trim() || Boolean(operacao)} onClick={() => void aoIniciar({ nome: nome.trim(), alvo: alvo.trim() })}>{operacao === "iniciar" ? <LoaderCircle className="size-3.5 animate-spin" /> : <Play className="size-3.5" />} Iniciar sessão beta</Botao></div>}</div></section>;
}
