import { Bell, BellOff, MoreHorizontal, Pause, Play, Trash2 } from "lucide-react";

import { tiposRotina } from "@/data/rotinas";
import type { RotinaAgendada } from "@/types/rotinas";

function formatarData(valor: number | null) {
  if (!valor) return "Sem próxima execução";
  return new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(valor));
}

export function ListaRotinas({ rotinas, selecionadaId, aoSelecionar, aoAlternar, aoExecutar, aoRemover }: { rotinas: RotinaAgendada[]; selecionadaId: string | null; aoSelecionar: (id: string) => void; aoAlternar: (id: string, ativa: boolean) => Promise<void>; aoExecutar: (id: string) => Promise<unknown>; aoRemover: (id: string) => Promise<void> }) {
  return <section className="rounded-md border border-[#e1e7e6] bg-white"><div className="flex items-center justify-between border-b border-[#edf0ef] px-4 py-3"><div><h2 className="text-[10px] font-semibold text-[#303737]">Rotinas cadastradas</h2><p className="mt-0.5 text-[8px] text-[#929a99]">Agendamentos persistidos no SQLite local.</p></div><MoreHorizontal className="size-4 text-[#9aa1a0]" /></div><div className="divide-y divide-[#edf0ef]">{rotinas.length === 0 && <div className="px-4 py-12 text-center text-[9px] text-[#929a99]">Nenhuma rotina cadastrada.</div>}{rotinas.map((rotina) => { const tipo = tiposRotina.find((item) => item.id === rotina.tipo); const Icone = tipo?.icone ?? Bell; return <article key={rotina.id} className={`cursor-pointer px-4 py-3 transition hover:bg-[#f8faf9] ${selecionadaId === rotina.id ? "bg-[#f1f8f6]" : ""}`} onClick={() => aoSelecionar(rotina.id)}><div className="flex items-start gap-3"><div className="grid size-8 shrink-0 place-items-center rounded-md bg-[#edf6f3] text-[#268a76]"><Icone className="size-3.5" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate text-[9.5px] font-medium text-[#343b3a]">{rotina.nome}</strong><span className={`rounded-full px-1.5 py-0.5 text-[7px] font-medium ${rotina.ativa ? "bg-[#e6f4ef] text-[#207762]" : "bg-[#f0f1f1] text-[#7f8786]"}`}>{rotina.ativa ? "Ativa" : "Pausada"}</span>{rotina.notificar ? <Bell className="size-3 text-[#67807a]" /> : <BellOff className="size-3 text-[#a4abaa]" />}</div><p className="mt-1 truncate text-[8px] text-[#8d9594]">{tipo?.titulo} · {formatarData(rotina.proximaExecucaoEm)}</p><p className="mt-1 text-[7.5px] text-[#a0a6a5]">Último estado: {rotina.ultimoStatus ?? "ainda não executada"}</p></div><div className="flex shrink-0 items-center gap-1" onClick={(evento) => evento.stopPropagation()}><button type="button" aria-label="Executar agora" onClick={() => void aoExecutar(rotina.id)} className="foco-acessivel grid size-7 place-items-center rounded-md text-[#697372] hover:bg-[#edf2f1]"><Play className="size-3" /></button><button type="button" aria-label={rotina.ativa ? "Pausar rotina" : "Ativar rotina"} onClick={() => void aoAlternar(rotina.id, !rotina.ativa)} className="foco-acessivel grid size-7 place-items-center rounded-md text-[#697372] hover:bg-[#edf2f1]">{rotina.ativa ? <Pause className="size-3" /> : <Play className="size-3" />}</button><button type="button" aria-label="Excluir rotina" onClick={() => void aoRemover(rotina.id)} className="foco-acessivel grid size-7 place-items-center rounded-md text-[#a75b5b] hover:bg-[#fbf0f0]"><Trash2 className="size-3" /></button></div></div></article>;})}</div></section>;
}
