"use client";

import { Ban, Play, Save, SlidersHorizontal } from "lucide-react";
import { Botao } from "@/components/ui/botao";
import { CampoFormulario, classesCampo } from "@/components/ui/campo-formulario";
import { idiomasLaboratorio, plataformasLaboratorio, provedoresLaboratorio } from "@/data/laboratorio-ia";
import type { ConfiguracaoNovoExperimento, ExperimentoLaboratorio } from "@/types/laboratorio-ia";
import type { IdProvedorIa } from "@/types/provedores-ia";

export function PainelConfiguracaoExperimento({ experimento, executando, aoAtualizar, aoExecutar, aoCancelar, aoSalvarPreset }: {
  experimento:ExperimentoLaboratorio; executando:boolean; aoAtualizar:(alteracoes:Partial<ConfiguracaoNovoExperimento>)=>void;
  aoExecutar:()=>void; aoCancelar:()=>void; aoSalvarPreset:()=>void;
}) {
  return <section className="painel-superficie overflow-hidden rounded-md"><header className="flex items-start justify-between gap-4 border-b border-[#e7ebeb] bg-[#fafbfb] px-4 py-3.5"><div><h2 className="text-[10px] font-semibold text-[#303637]">Configuração do experimento</h2><p className="mt-1 text-[8px] leading-3.5 text-[#8b9293]">Execute com provedores reais ou mantenha a demonstração explícita para testes de interface.</p></div><span className="inline-flex h-7 items-center gap-1.5 rounded-md border border-[#dfe5e4] bg-white px-2 text-[7.5px] font-medium text-[#727a7b]"><SlidersHorizontal className="size-3" /> Provedores reais</span></header>
  <div className="space-y-4 p-4"><div className="grid grid-cols-2 gap-3"><CampoFormulario rotulo="Nome do experimento"><input value={experimento.nome} onChange={(e)=>aoAtualizar({nome:e.target.value})} className={`${classesCampo} h-9`} /></CampoFormulario><CampoFormulario rotulo="Modo de execução"><select value={experimento.modoExecucao} onChange={(e)=>aoAtualizar({modoExecucao:e.target.value as "real"|"demonstracao"})} className={`${classesCampo} h-9`}><option value="real">Real · usar API configurada</option><option value="demonstracao">Demonstração · sem chamada externa</option></select></CampoFormulario></div>
  <div className="grid grid-cols-[1fr_1fr_160px] gap-3 rounded-md border border-[#dfeae7] bg-[#f6faf9] p-3"><CampoFormulario rotulo="Provedor preferido"><select value={experimento.provedorPreferido} disabled={experimento.modoExecucao!=="real"} onChange={(e)=>aoAtualizar({provedorPreferido:e.target.value as IdProvedorIa|"automatico"})} className={`${classesCampo} h-9 bg-white`}>{provedoresLaboratorio.map((p)=><option key={p.id} value={p.id}>{p.titulo}</option>)}</select></CampoFormulario><CampoFormulario rotulo="Máximo de tokens"><input type="number" min={64} max={64000} disabled={experimento.modoExecucao!=="real"} value={experimento.maxTokensSaida} onChange={(e)=>aoAtualizar({maxTokensSaida:Number(e.target.value)})} className={`${classesCampo} h-9 bg-white`} /></CampoFormulario><label className="flex items-end pb-1"><span className="flex h-9 w-full items-center justify-between rounded-md border border-[#dfe5e4] bg-white px-3 text-[7.5px] text-[#5f6869]">Permitir fallback<input type="checkbox" disabled={experimento.modoExecucao!=="real"} checked={experimento.permitirFallback} onChange={(e)=>aoAtualizar({permitirFallback:e.target.checked})} className="size-4 accent-[#238771]" /></span></label></div>
  <CampoFormulario rotulo="Tema ou contexto" descricao="Use uma descrição concreta para manter as versões comparáveis."><textarea value={experimento.tema} onChange={(e)=>aoAtualizar({tema:e.target.value})} rows={3} className={`${classesCampo} resize-y py-2.5 leading-4`} /></CampoFormulario>
  <div className="grid grid-cols-3 gap-3"><CampoFormulario rotulo="Público"><input value={experimento.publico} onChange={(e)=>aoAtualizar({publico:e.target.value})} className={`${classesCampo} h-9`} /></CampoFormulario><CampoFormulario rotulo="Plataforma"><select value={experimento.plataforma} onChange={(e)=>aoAtualizar({plataforma:e.target.value})} className={`${classesCampo} h-9`}>{plataformasLaboratorio.map((p)=><option key={p}>{p}</option>)}</select></CampoFormulario><CampoFormulario rotulo="Idioma"><select value={experimento.idioma} onChange={(e)=>aoAtualizar({idioma:e.target.value})} className={`${classesCampo} h-9`}>{idiomasLaboratorio.map((i)=><option key={i}>{i}</option>)}</select></CampoFormulario></div>
  <CampoFormulario rotulo="Prompt do sistema" descricao="Define o papel, as restrições e o padrão editorial da IA."><textarea value={experimento.promptSistema} onChange={(e)=>aoAtualizar({promptSistema:e.target.value})} rows={4} className={`${classesCampo} resize-y py-2.5 leading-4`} /></CampoFormulario>
  <CampoFormulario rotulo="Instrução do experimento" descricao="Escreva o que deve mudar entre as variações e o que precisa permanecer igual."><textarea value={experimento.promptUsuario} onChange={(e)=>aoAtualizar({promptUsuario:e.target.value})} rows={5} className={`${classesCampo} resize-y py-2.5 leading-4`} /></CampoFormulario>
  <div className="grid grid-cols-[1fr_1fr_1.4fr] gap-3 rounded-md border border-[#e3e7e7] bg-[#fafbfb] p-3"><CampoFormulario rotulo="Variações"><select value={experimento.quantidadeVariacoes} onChange={(e)=>aoAtualizar({quantidadeVariacoes:Number(e.target.value)})} className={`${classesCampo} h-9 bg-white`}>{[1,2,3,4].map((q)=><option key={q} value={q}>{q} versão{q>1?"ões":""}</option>)}</select></CampoFormulario><CampoFormulario rotulo={`Criatividade · ${experimento.temperatura.toFixed(1)}`}><input type="range" min="0" max="2" step="0.1" value={experimento.temperatura} onChange={(e)=>aoAtualizar({temperatura:Number(e.target.value)})} className="mt-2 h-5 w-full accent-[#238771]" /></CampoFormulario><CampoFormulario rotulo="Observações" opcional><input value={experimento.observacoes} onChange={(e)=>aoAtualizar({observacoes:e.target.value})} placeholder="O que você pretende avaliar?" className={`${classesCampo} h-9 bg-white`} /></CampoFormulario></div></div>
  <footer className="flex items-center justify-between border-t border-[#e7ebeb] bg-[#fafbfb] px-4 py-3"><p className="max-w-[460px] text-[7.5px] leading-3.5 text-[#8b9293]">No modo real, tokens, custo estimado, latência, modelo e fallback ficam registrados em cada resultado.</p><div className="flex items-center gap-2"><Botao onClick={aoSalvarPreset} className="h-8 px-2.5 text-[9px]"><Save className="size-3.5" /> Salvar como preset</Botao>{executando ? <Botao onClick={aoCancelar} className="h-8 min-w-[142px] px-3 text-[9px]"><Ban className="size-3.5" /> Cancelar execução</Botao> : <Botao onClick={aoExecutar} variante="primario" className="h-8 min-w-[142px] px-3 text-[9px]"><Play className="size-3.5" /> Executar experimento</Botao>}</div></footer></section>;
}
