
import { FolderOpen, LoaderCircle } from "lucide-react";

import { Botao } from "@/components/ui/botao";
import type { EstruturaWorkspaceInstalacao } from "@/types/instalacao";

export function PainelWorkspace({ raiz, workspace, carregando, aoAlterar, aoPreparar, aoAbrir }: { raiz: string; workspace: EstruturaWorkspaceInstalacao | null; carregando: boolean; aoAlterar: (valor: string) => void; aoPreparar: () => void; aoAbrir: (caminho: string) => void }) {
  return <section className="rounded-md border border-[#e0e6e5] bg-white"><div className="border-b border-[#e7ebea] px-5 py-4"><h2 className="text-[12px] font-semibold text-[#303738]">Workspace permanente</h2><p className="mt-1 text-[8.5px] leading-4 text-[#7d8687]">Deixe o campo vazio para usar Documentos\\MakeFlux Studio ou informe uma pasta própria.</p></div><div className="p-5"><label className="block"><span className="mb-1.5 block text-[8px] font-medium text-[#596364]">Pasta principal</span><input value={raiz} onChange={(evento) => aoAlterar(evento.target.value)} placeholder="C:\\Users\\SeuUsuario\\Documents\\MakeFlux Studio" className="foco-acessivel h-10 w-full rounded-md border border-[#dfe5e4] bg-white px-3 text-[10px] text-[#3f4748] placeholder:text-[#a1a8a9]" /></label><div className="mt-3 flex gap-2"><Botao variante="primario" onClick={aoPreparar} disabled={carregando}>{carregando ? <LoaderCircle className="size-3.5 animate-spin" /> : <FolderOpen className="size-3.5" />} Preparar pastas</Botao>{workspace && <Botao onClick={() => aoAbrir(workspace.raiz)}><FolderOpen className="size-3.5" /> Abrir workspace</Botao>}</div>{workspace && <div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(workspace).filter(([chave, valor]) => typeof valor === "string" && chave !== "raiz").map(([chave, valor]) => <div key={chave} className="rounded-md border border-[#e4e9e8] bg-[#fafbfb] px-3 py-2"><span className="block text-[7px] uppercase tracking-[0.08em] text-[#92999a]">{chave}</span><span className="mt-1 block truncate text-[8px] text-[#4c5556]">{String(valor)}</span></div>)}</div>}</div></section>;
}
