
import { CheckCircle2, FolderOpen, GitBranch, LoaderCircle, Play } from "lucide-react";

import { Botao } from "@/components/ui/botao";
import type { DiagnosticoInstalacaoAssistida, ResultadoInstalacaoMoneyPrinter } from "@/types/instalacao";

export function PainelMoneyPrinter({ diagnostico, resultado, operacao, aoInstalar, aoAbrir }: { diagnostico: DiagnosticoInstalacaoAssistida | null; resultado: ResultadoInstalacaoMoneyPrinter | null; operacao: string | null; aoInstalar: () => void; aoAbrir: (caminho: string) => void }) {
  const diretorio=resultado?.diretorio ?? diagnostico?.diretorioMoneyPrinter;
  const pronto=Boolean(diagnostico?.prontoParaMotor);
  return <section className="rounded-md border border-[#e0e6e5] bg-white"><div className="border-b border-[#e7ebea] px-5 py-4"><h2 className="text-[12px] font-semibold text-[#303738]">MoneyPrinterTurbo</h2><p className="mt-1 text-[8.5px] leading-4 text-[#7d8687]">Clona o repositório oficial, instala Python 3.11 pelo uv, sincroniza o ambiente bloqueado e cria o config.toml.</p></div><div className="p-5"><div className="grid grid-cols-3 gap-3"><div className="rounded-md border border-[#e3e8e7] bg-[#fafbfb] p-3"><GitBranch className="size-3.5 text-[#657071]" /><strong className="mt-2 block text-[9px] text-[#3d4546]">Repositório</strong><span className="mt-1 block text-[7.5px] text-[#899192]">{diagnostico?.moneyPrinterDetectado ? "Detectado" : "Será clonado"}</span></div><div className="rounded-md border border-[#e3e8e7] bg-[#fafbfb] p-3"><Play className="size-3.5 text-[#657071]" /><strong className="mt-2 block text-[9px] text-[#3d4546]">Ambiente Python</strong><span className="mt-1 block text-[7.5px] text-[#899192]">{diagnostico?.ambientePythonPronto ? "Sincronizado" : "uv sync --frozen"}</span></div><div className="rounded-md border border-[#e3e8e7] bg-[#fafbfb] p-3"><CheckCircle2 className="size-3.5 text-[#657071]" /><strong className="mt-2 block text-[9px] text-[#3d4546]">Configuração</strong><span className="mt-1 block text-[7.5px] text-[#899192]">{diagnostico?.configCriada ? "config.toml criada" : "Pendente"}</span></div></div>{diretorio && <div className="mt-3 rounded-md border border-[#e1e7e6] bg-white px-3 py-2 text-[8px] text-[#5e6869]">{diretorio}</div>}<div className="mt-3 flex gap-2"><Botao variante="primario" onClick={aoInstalar} disabled={!pronto || Boolean(operacao)}>{operacao === "motor" ? <LoaderCircle className="size-3.5 animate-spin" /> : <Play className="size-3.5" />}{diagnostico?.moneyPrinterDetectado ? "Sincronizar novamente" : "Instalar motor"}</Botao>{diretorio && <Botao onClick={() => aoAbrir(diretorio)}><FolderOpen className="size-3.5" /> Abrir pasta</Botao>}</div>{!pronto && <p className="mt-3 text-[7.5px] leading-4 text-[#9a7130]">Prepare o workspace e instale Git, uv, FFmpeg e ImageMagick antes de continuar.</p>}</div></section>;
}
