
import { CheckCircle2, CircleAlert, Download, LoaderCircle } from "lucide-react";

import { Botao } from "@/components/ui/botao";
import type { DependenciaInstalacao, IdDependenciaInstalacao } from "@/types/instalacao";

export function PainelDependencias({ dependencias, operacao, winget, aoInstalar }: { dependencias: DependenciaInstalacao[]; operacao: string | null; winget: boolean; aoInstalar: (id: IdDependenciaInstalacao) => void }) {
  return <section className="rounded-md border border-[#e0e6e5] bg-white"><div className="border-b border-[#e7ebea] px-5 py-4"><h2 className="text-[12px] font-semibold text-[#303738]">Dependências do computador</h2><p className="mt-1 text-[8.5px] leading-4 text-[#7d8687]">O assistente usa apenas pacotes WinGet previamente aprovados.</p></div><div className="divide-y divide-[#edf0ef]">{dependencias.map((item) => { const instalando=operacao===`dependencia:${item.id}`; return <article key={item.id} className="flex items-center gap-4 px-5 py-3.5"><span className={`grid size-8 place-items-center rounded-md ${item.disponivel ? "bg-[#e8f5f1] text-[#257763]" : "bg-[#fff6e8] text-[#9a7130]"}`}>{item.disponivel ? <CheckCircle2 className="size-4" /> : <CircleAlert className="size-4" />}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="text-[9px] text-[#394142]">{item.nome}</strong>{item.obrigatoria && <span className="rounded bg-[#f0f3f3] px-1.5 py-0.5 text-[6px] font-semibold uppercase tracking-[0.08em] text-[#737d7e]">Obrigatória</span>}</div><p className="mt-0.5 truncate text-[7.5px] text-[#8a9293]">{item.disponivel ? `${item.versao ?? "Detectada"} · ${item.caminho ?? "caminho gerenciado"}` : item.mensagem}</p></div><Botao onClick={() => aoInstalar(item.id)} disabled={item.disponivel || !winget || Boolean(operacao)}>{instalando ? <LoaderCircle className="size-3.5 animate-spin" /> : <Download className="size-3.5" />}{item.disponivel ? "Pronta" : "Instalar"}</Botao></article>; })}</div>{!winget && <div className="border-t border-[#eadfca] bg-[#fffaf0] px-5 py-3 text-[8px] leading-4 text-[#876b37]">O WinGet não foi detectado. Atualize o “App Installer” do Windows antes de usar a instalação automática.</div>}</section>;
}
