import { ExternalLink, KeyRound, Link2Off } from "lucide-react";

import { Botao } from "@/components/ui/botao";
import { provedoresCanais, rotulosStatusConexao } from "@/data/canais-publicacao";
import type { ConexaoCanalPublicacao, ProvedorCanalPublicacao } from "@/types/canais-publicacao";

export function CartaoCanal({ provedor, conexao, aoConectar, aoDesconectar }: { provedor: ProvedorCanalPublicacao; conexao: ConexaoCanalPublicacao | null; aoConectar: () => void; aoDesconectar: () => void }) {
  const dados = provedoresCanais.find((item) => item.id === provedor) ?? provedoresCanais[0];
  const Icone = dados.icone;
  return <article className="rounded-md border border-[#e0e6e5] bg-white p-4"><div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-md text-white" style={{ backgroundColor: dados.cor }}><Icone className="size-4.5" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="text-[10px] font-semibold text-[#303737]">{dados.titulo}</h3><span className={`rounded-full px-2 py-1 text-[6.5px] font-medium ${conexao ? "bg-[#eaf6f2] text-[#247360]" : "bg-[#f1f3f3] text-[#788180]"}`}>{conexao ? rotulosStatusConexao[conexao.status] : "Não conectada"}</span></div><p className="mt-1 text-[7.5px] leading-3.5 text-[#858e8d]">{dados.descricao}</p></div></div>{conexao ? <div className="mt-4 rounded-md bg-[#f7f9f9] px-3 py-2"><div className="flex justify-between gap-2 text-[7.5px]"><span className="text-[#8b9392]">Conta</span><strong className="truncate text-[#4a5352]">{conexao.contaNome || conexao.contaId || "Conta autorizada"}</strong></div><div className="mt-1 flex justify-between gap-2 text-[7px]"><span className="text-[#969d9c]">Escopos</span><span className="truncate text-[#798281]">{conexao.escopos.join(", ")}</span></div></div> : <div className="mt-4 rounded-md border border-dashed border-[#dce3e2] px-3 py-2 text-[7.5px] leading-3.5 text-[#8d9594]">Use as credenciais OAuth do seu aplicativo aprovado no portal da plataforma.</div>}<div className="mt-3 flex gap-2">{conexao ? <Botao className="w-full" onClick={aoDesconectar}><Link2Off className="size-3.5" /> Desconectar</Botao> : <Botao variante="primario" className="w-full" onClick={aoConectar}><KeyRound className="size-3.5" /> Conectar por OAuth</Botao>}<button type="button" onClick={() => window.open("/central-de-ajuda?secao=guias", "_self")} className="foco-acessivel grid size-8 shrink-0 place-items-center rounded-md border border-[#dde3e2] text-[#737d7c]"><ExternalLink className="size-3.5" /></button></div></article>;
}
